import {version} from './src/environments/version';
import * as envjson from './src/environments/environment.prod';

import { writeFileSync, readFileSync } from 'fs';

let major = version.major;
let minor = version.minor;
let build = version.build || 0;
let updatedBuild = build + 1;

writeFileSync('./src/environments/version.ts', `
//Autogenerated Version File
export const version = {major:${major}, minor:${minor}, build:${updatedBuild}};
 `
);

console.log(envjson);

